In [1]:
import numpy as np
from sklearn import preprocessing

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
x = np.array([[ 1.,-1., 2.],
              [ 2., 0., 0.],
              [ 0., 1.,-1.]])

In [3]:
x_scaled = preprocessing.scale(x)

In [4]:
print(x_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [6]:
print(x_scaled.mean(axis=0))

[0. 0. 0.]


In [13]:
print(x_scaled.std(axis=0))

[1. 1. 1.]


# Scaler
Using Standard scaler with default values: mean=0,variance=1

In [9]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

StandardScaler()

In [10]:
print(scaler.transform(x))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
x_test = [[1.,1.,0.]]
print(scaler.transform(x_test))

[[ 0.          1.22474487 -0.26726124]]


Standard Scaler with different mean and variance

In [21]:
print("Training data: ",x)
scaler2 = preprocessing.StandardScaler(with_mean=1,with_std=4)
scaler2.fit(x)
print(scaler2.transform(x))
print("Testing data: ",x_test)
print(scaler2.transform(x_test))

Training data:  [[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
Testing data:  [[1.0, 1.0, 0.0]]
[[ 0.          1.22474487 -0.26726124]]


Absolute Maximum Scaler: every value divided by max

In [25]:
print("Training data:\n",x)
scaler3 = preprocessing.MaxAbsScaler()
scaler3.fit(x)
print("Scaled train:\n",scaler3.transform(x))
print("Testing data:\n",x_test)
print("Scaled  Test:\n",scaler3.transform(x_test))

Training data:
 [[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
Scaled train:
 [[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]
Testing data:
 [[1.0, 1.0, 0.0]]
Scaled  Test:
 [[0.5 1.  0. ]]


Min Max Scaler: every value changed to range [0,1]

In [27]:
print("Training data:\n",x)
scaler4 = preprocessing.MinMaxScaler()
scaler4.fit(x)
print("Scaled train:\n",scaler4.transform(x))
print("Testing data:\n",x_test)
print("Scaled  Test:\n",scaler4.transform(x_test))

Training data:
 [[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
Scaled train:
 [[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
Testing data:
 [[1.0, 1.0, 0.0]]
Scaled  Test:
 [[0.5        1.         0.33333333]]
