In [1]:
from sklearn import datasets
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
iris = datasets.load_iris()

In [3]:
x1,x2,y1,y2 = model_selection.train_test_split(iris.data,iris.target)

In [4]:
clf = DecisionTreeClassifier()

In [5]:
clf.fit(x1,y1)

DecisionTreeClassifier()

In [13]:
import pydotplus

In [14]:
dot_data = export_graphviz(clf,out_file=None,feature_names=iris.feature_names,class_names=iris.target_names)

In [15]:
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf("grph.pdf")

True

In [8]:
y_2_p = clf.predict(x2)
y_1_p = clf.predict(x1)

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
print(confusion_matrix(y2,y_2_p))

[[14  0  0]
 [ 0  7  2]
 [ 0  1 14]]


In [11]:
print(confusion_matrix(y1,y_1_p))

[[36  0  0]
 [ 0 41  0]
 [ 0  0 35]]
