In [2]:
from sklearn import datasets
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import numpy as np

In [3]:
data = datasets.load_iris()
x = data.data
y = data.target

In [4]:
x1,x2,y1,y2 = model_selection.train_test_split(x,y)

In [5]:
alg = LogisticRegression()

In [7]:
alg.fit(x1,y1)

LogisticRegression()

In [8]:
y_train_pred = alg.predict(x1)
y_test_pred = alg.predict(x2)

In [9]:
from sklearn.metrics import confusion_matrix

In [10]:
print(confusion_matrix(y1,y_train_pred))
print(confusion_matrix(y2,y_test_pred))

[[38  0  0]
 [ 0 29  3]
 [ 0  0 42]]
[[12  0  0]
 [ 0 18  0]
 [ 0  1  7]]


In [11]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y1,y))