In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("sample.csv")

In [4]:
print(df)

  x1 x2 x3  y
0  a  x  p  1
1  a  x  q  2
2  b  y  q  3
3  b  x  p  1
4  c  z  r  3
5  c  x  q  2
6  b  z  p  1


In [16]:
y = df['y'].to_numpy()
print(y)

[1 2 3 1 3 2 1]


In [14]:
x = df.iloc[:,df.columns!='y'].to_numpy()
print(x)

[['a' 'x' 'p']
 ['a' 'x' 'q']
 ['b' 'y' 'q']
 ['b' 'x' 'p']
 ['c' 'z' 'r']
 ['c' 'x' 'q']
 ['b' 'z' 'p']]


In [22]:
print(x[0])

['a' 'x' 'p']


In [90]:
def fillDict(x_train,y_train):
    result = initDict(x_train,y_train)
    for i in range(len(x_train)):
        result["total_data"] = result.get("total_data",0) +1
        result[y_train[i]]["total"] = ((result.get(y_train[i],{})).get("total",0)) +1
        for j in range(len(x_train[0])):
            result[y_train[i]][j][x_train[i,j]] = result.get(y_train[i],{}).get(j,{}).get(x_train[i,j],0)+1
    return result

In [91]:
dic = fillDict(x,y)
print(dic)

{'total_data': 7, 1: {'total': 3, 0: {'c': 0, 'a': 1, 'b': 2}, 1: {'z': 1, 'x': 2, 'y': 0}, 2: {'q': 0, 'r': 0, 'p': 3}}, 2: {'total': 2, 0: {'c': 1, 'a': 1, 'b': 0}, 1: {'z': 0, 'x': 2, 'y': 0}, 2: {'q': 2, 'r': 0, 'p': 0}}, 3: {'total': 2, 0: {'c': 1, 'a': 0, 'b': 1}, 1: {'z': 1, 'x': 0, 'y': 1}, 2: {'q': 1, 'r': 1, 'p': 0}}}


In [97]:
def predict(dictionary,x_test):
    res = 0
    ans = -1
    for y in dictionary:
#         print(dictionary[y]["total"])
#         print(dictionary["total_data"])
        if y!= 'total_data':
            p = (dictionary[y]["total"]/dictionary["total_data"])
            p=1
            for i in range(len(x_test)):
                p*=((dictionary[y][i][x_test[i]]))
            p/=(dictionary[y]["total"])
            if p>ans:
                ans = p
                res = y
    return res
print(predict(dic,['a','x','r']))

1


In [102]:
def predictLaplace(dictionary,x_test):
    res = 0
    ans = -1
    for y in dictionary:
        if y!='total_data':
            p = np.log((dictionary[y]["total"]) - np.log(dictionary["total_data"]))
            for i in range(len(x_test)):
                z=(((dictionary[y][i][x_test[i]])+1)/(dictionary[y]["total"]*(len(dictionary[y][i].keys()))))
                p+=np.log(z)
            if p>ans:
                ans = p
                res = y
    return res

In [115]:
def predictAll(dic,x_test):
    y_p = []
    for x in x_test:
        y_p.append(predictLaplace(dic,x))
    return y_p

In [103]:
print(predictLaplace(dic,['a','x','r']))

0


In [104]:
from sklearn import datasets

In [107]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [108]:
def makeLabel(col):
    mn = col.min()
    mx = col.max()
    second = col.mean()
    first = (mn+second)/2
    third = (mx+second)/2
    for i in range(len(col)):
        if col[i]<first:
            col[i] = 0
        elif col[i]<second:
            col[i] = 1
        elif col[i]<third:
            col[i] = 2
        else:
            col[i] = 3
    return col

In [110]:
for i in range(x.shape[-1]):
    x[:,i] = makeLabel(x[:,i])

In [111]:
print(x)

[[1. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [1. 3. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 3. 0. 0.]
 [1. 3. 0. 0.]
 [1. 3. 0. 0.]
 [1. 2. 0. 0.]
 [1. 3. 0. 0.]
 [1. 3. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 3. 0. 0.]
 [1. 3. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [1. 3. 0. 0.]
 [0. 1. 0. 0.]
 [1. 3. 0. 0.]
 [0. 2. 0. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 0.]
 [3. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 2. 2. 2.]
 [1. 0. 2. 2.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [2. 2. 2. 2.]
 [0. 0. 1. 1.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [0. 0. 1. 1.]
 [2. 1. 2. 2.]
 [2. 0. 2. 1.]
 [2. 1. 2. 2.]
 [1. 1. 1. 2.]
 [2. 2. 2. 2.]
 [1. 1. 2.

In [106]:
from sklearn import model_selection
x1,x2,y1,y2 = model_selection.train_test_split(x,y)

In [112]:
diccc = fillDict(x1,y1)


In [114]:
print(diccc)

{'total_data': 112, 0: {'total': 37, 0: {4.6: 4, 5.0: 8, 5.9: 0, 6.6: 0, 6.4: 0, 6.2: 0, 4.8: 3, 6.3: 0, 6.9: 0, 7.2: 0, 5.1: 5, 6.7: 0, 7.0: 0, 4.9: 4, 4.4: 3, 5.4: 3, 5.5: 1, 5.6: 0, 6.1: 0, 6.0: 0, 6.5: 0, 7.4: 0, 7.9: 0, 7.6: 0, 4.7: 1, 5.8: 1, 5.7: 1, 5.3: 1, 5.2: 2, 6.8: 0, 7.7: 0}, 1: {2.9: 1, 3.6: 3, 3.0: 3, 3.1: 4, 2.8: 0, 2.5: 0, 3.2: 4, 3.4: 8, 3.8: 2, 2.4: 0, 4.4: 1, 2.0: 0, 3.5: 4, 4.0: 1, 4.1: 1, 2.6: 0, 2.7: 0, 2.2: 0, 3.3: 2, 3.7: 2, 3.9: 1}, 2: {1.0: 1, 1.6: 6, 3.8: 0, 4.6: 0, 5.6: 0, 5.1: 0, 4.3: 0, 5.0: 0, 5.7: 0, 6.1: 0, 5.2: 0, 4.7: 0, 1.5: 9, 6.0: 0, 6.9: 0, 3.0: 0, 3.5: 0, 4.1: 0, 4.9: 0, 4.5: 0, 4.4: 0, 4.0: 0, 5.5: 0, 5.4: 0, 6.4: 0, 6.6: 0, 1.7: 3, 1.2: 2, 3.3: 0, 3.7: 0, 4.2: 0, 1.3: 5, 4.8: 0, 5.8: 0, 6.7: 0, 1.4: 9, 1.9: 2, 3.9: 0}, 3: {0.2: 26, 1.8: 0, 2.1: 0, 1.9: 0, 1.3: 0, 2.3: 0, 2.5: 0, 2.4: 0, 1.1: 0, 1.4: 0, 1.6: 0, 1.5: 0, 1.0: 0, 0.5: 1, 2.0: 0, 0.6: 1, 1.7: 0, 1.2: 0, 0.1: 3, 2.2: 0, 0.3: 2, 0.4: 4}}, 1: {'total': 36, 0: {4.6: 0, 5.0: 1, 5.9: 2, 

In [116]:
y_pred = predictAll(diccc,x2)

KeyError: 2.3